import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  folder1,
  folder2,
}: {
  children: React.ReactNode;
  folder1: React.ReactNode;
  folder2: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ padding: "50px" }}>
        <h1>parallel routes</h1>
        <div style={{ padding: "20px",background:"yellow",color:"red" }}>{folder1}</div>
        <div style={{ padding: "20px" }}>{folder2}</div>

        {children}
      </body>
    </html>
  );
}
